# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 12:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('custId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderNum', models.IntegerField(primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=50)),
                ('customerSurname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=75)),
                ('postalCode', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('totalPrice', models.FloatField()),
                ('custId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('orderNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productNum', models.IntegerField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('productPrice', models.FloatField()),
                ('productRating', models.IntegerField(max_length=1)),
                ('stock', models.IntegerField()),
                ('productDescription', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('imageLink', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=30)),
                ('total', models.IntegerField(verbose_name=4)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WhishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Customer')),
                ('productNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Products')),
            ],
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='productNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Products'),
        ),
        migrations.AlterUniqueTogether(
            name='whishlist',
            unique_together=set([('custId', 'productNum')]),
        ),
        migrations.AlterUniqueTogether(
            name='orderdetails',
            unique_together=set([('orderNum', 'productNum')]),
        ),
    ]
