# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20171010_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prodName',
            field=models.CharField(max_length=200),
        ),
    ]
