# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20171011_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prodPrice',
            field=models.DecimalField(decimal_places=2, max_digits=999),
        ),
    ]