# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20171013_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('amount', models.IntegerField()),
                ('prodNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Products')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together=set([('session_key', 'prodNum')]),
        ),
    ]
