# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20171024_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='custId',
            field=models.ForeignKey(db_column='custId', on_delete=django.db.models.deletion.CASCADE, to='store.Customers'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='productNum',
            field=models.ForeignKey(db_column='productNum', on_delete=django.db.models.deletion.CASCADE, to='store.Products'),
        ),
    ]
