# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20171025_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='orderNum',
            field=models.ForeignKey(db_column='orderNum', on_delete=django.db.models.deletion.CASCADE, to='store.Orders'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='productNum',
            field=models.ForeignKey(db_column='productNum', on_delete=django.db.models.deletion.CASCADE, to='store.Products'),
        ),
    ]
