# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20171029_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='customerID',
            field=models.ForeignKey(db_column='customerID', default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Customers'),
            preserve_default=False,
        ),
    ]
