# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_orders_customerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customerID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customers',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customers',
            name='surname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customers',
            name='telephone',
            field=models.CharField(max_length=12),
        ),
    ]
