# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20171029_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='customerID',
            field=models.ForeignKey(db_column='customerID', on_delete=django.db.models.deletion.CASCADE, to='store.Customers'),
        ),
    ]
